; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps = 
    bblanchon/ArduinoJson
    bodmer/TFT_eSPI
monitor_speed = 115200

build_flags=
    -D USER_SETUP_LOADED=1
    -D ST7735_DRIVER=1
    -D TFT_WIDTH=128
    -D TFT_HEIGHT=160
    -D ST7735_GREENTAB
    -D TFT_MOSI=23
    -D TFT_SCLK=18
    -D TFT_CS=15
    -D TFT_DC=2
    -D TFT_RST=4
    -D SPI_FREQUENCY=27000000
    -D LOAD_GLCD=1      ; built-in 8px font (font 1, the default)
    -D LOAD_FONT2=1     ; 16px font
    -D LOAD_FONT4=1     ; 26px font
    -D LOAD_FONT6=1     ; 48px digits
    -D LOAD_FONT7=1     ; 7-seg style digits
    -D LOAD_FONT8=1     ; 75px digits
    -D SMOOTH_FONT=1    ; anti-aliased fonts
